import assert from 'node:assert/strict';
import fs from 'node:fs';

const page = fs.readFileSync('items/QRCode.html', 'utf8');

assert.match(page, /cdnjs\.cloudflare\.com\/ajax\/libs\/qrcode\/1\.5\.1\/qrcode\.min\.js/);
assert.match(page, /qrcode-core\.js/);
assert.match(page, /theme\.js/);
assert.match(page, /17tools-qrcode/);
assert.match(page, /<title>二维码工具<\/title>/);
assert.match(page, /data-type="text"/);
assert.match(page, /data-type="url"/);
assert.match(page, /data-type="wifi"/);
assert.match(page, /data-type="vcard"/);
assert.match(page, /data-type="email"/);
assert.match(page, /data-type="tel"/);
assert.match(page, /data-type="sms"/);
assert.match(page, /id="btnPng"/);
assert.match(page, /id="btnSvg"/);
assert.match(page, /id="btnCopy"/);
assert.match(page, /id="previewCanvas"/);
assert.match(page, /class="form-input"/);
assert.match(page, /errorCorrectionLevel/);
assert.match(page, /margin:\s*2/);
assert.match(page, /150/);
assert.equal(page.includes('innerHTML'), false);
assert.equal(page.includes('alert('), false);
assert.match(page, /填写内容后生成二维码/);
assert.match(page, /二维码库加载失败/);
assert.match(page, /无法复制，请改用下载/);
assert.match(page, /已复制到剪贴板/);
assert.match(page, /无法生成二维码，请缩短内容/);
assert.match(page, /前景与背景对比过低，可能无法扫描/);
assert.match(page, /决定图案被遮挡或印刷模糊时还能不能扫出来/);
assert.match(page, /WPA \/ WPA2/);

const index = fs.readFileSync('index.html', 'utf8');
const welcome = fs.readFileSync('items/Welcome.html', 'utf8');
const history = fs.readFileSync('items/History.html', 'utf8');
const version = fs.readFileSync('js/version.js', 'utf8');
const readme = fs.readFileSync('README.md', 'utf8');

const imageIndex = index.indexOf('data-file="ImageProcessor.html"');
const qrIndex = index.indexOf('data-file="QRCode.html"');
const regexIndex = index.indexOf('data-file="Regex.html"');
assert.ok(imageIndex !== -1 && qrIndex !== -1 && regexIndex !== -1, '导航缺少图片处理、二维码或正则入口');
assert.ok(qrIndex > imageIndex, '二维码工具应在图片处理之后');
assert.ok(qrIndex < regexIndex, '二维码工具应在正则表达式之前');
assert.match(index, /二维码工具/);
assert.equal(/data-file="QRCode.html"[^>]*data-protected/.test(index), false);

assert.match(welcome, /19个实用工具/);
assert.match(welcome, /v2\.16\.3/);
assert.match(history, /<!-- 版本 2\.16\.3 -->/);
assert.match(history, /版本 2\.16\.3/);
assert.match(history, /<!-- 版本 2\.16\.2 -->/);
assert.match(history, /版本 2\.16\.2/);
assert.match(history, /<!-- 版本 2\.16\.1 -->/);
assert.match(history, /版本 2\.16\.1/);
assert.match(history, /<!-- 版本 2\.16\.0 -->/);
assert.match(history, /版本 2\.16\.0/);
assert.match(history, /2026-08-17/);
assert.match(history, /2026-08-16/);
assert.match(history, /2026-08-13/);
assert.match(history, /工具加载超过 1 秒/);
assert.match(history, /未保存输入保护/);
assert.match(history, /二维码工具/);
assert.match(history, /智能白板/);
assert.match(history, /无限|右键/);
assert.match(version, /2\.16\.3/);
assert.equal(version.includes('2.16.2'), false);
assert.equal(version.includes('2.16.1'), false);
assert.equal(version.includes('2.16.0'), false);
assert.equal(version.includes('2.15.2'), false);
assert.match(readme, /二维码工具/);
assert.match(readme, /QRCode\.html/);
assert.match(readme, /qrcode-core\.js/);

console.log('qrcode-page regression passed');
